---
title: "The VectorBiTE Training Materials"
description: |
  Links to all course materials
output: 
  distill::distill_article:
    toc: true 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


# Overview to the materials

<br>
<br>

# Pre-work and set-up

### Hardware and Software

We will be using [R](https://cran.r-project.org/) for all data manipulation and analyses/model fitting. Any operating system (Windows, Mac, Linux) will do, as long as you have R (version 3.6 or higher) installed.

You may use any IDE/ GUI for R (VScode, RStudio, Emacs, etc). For most people, [RStudio](https://www.rstudio.com/) is a good option. Whichever one you decide to use, please make sure it is installed and test it before the workshop. We will have a channel on slack dedicated to software/hardware issues and troubleshooting.

We will also be using Zoom and Slack to facilitate the synchronous portions of the training. Please have these installed in advance. 

### Pre-requisites

We are assuming familiarity with R basics. In addition, we recommend that you do the following:

1. Go to [The Multilingual Quantitative Biologist](https://mhasoba.github.io/TheMulQuaBio/intro.html), and read+work through the [Biological Computing in R Chapter](https://mhasoba.github.io/TheMulQuaBio/notebooks/07-R.html) up to the section on Writing R code. Of course, keep going if you want (although we will cover some similar materials here).

2. In addition / alternatively to pre-work element (1), here are some resources for brushing up on R [at the end of the Intro R Chapter you can try](https://mhasoba.github.io/TheMulQuaBio/notebooks/07-R.html#readings-and-resources). But there are many more resources online (e.g., [this](https://www.codecademy.com/learn/learn-r) and [this](https://www.dataquest.io/blog/learn-r-for-data-science/) ) -- pick something that suits your learning style.

3. Review background on [introductory probability and statistics](activities/Stats_review.html) ([solutions to exercises](activities/Stats_review_soln.html)) 

4. Inculcate the coding Jedi inside of you - or the Sith - whatever works.


# Introduction to the VectorByte databases^[What is the difference between VectorBiTE and VectorByte? We are glad you asked! [VectorBiTE](http://vectorbite.org/) is an RCN or a research coordination network funded by a 5 year grant from the BBSRC. VectorBiTE is hosting this training as it transitions into [VectorByte](https://www.vectorbyte.org/) which is a newly funded NSF grant to establish a global open access data platform to study disease vectors. All the databases are transitioning to VectorByte but the legacy options will still be available on the VectorByte website.]

- This component will be delivered live & synchronously (with a recording to be uploaded later)

# Beginner materials

### Data Wrangling in R

- [Self-Guided Activity](activities/VB_Datawrangling_exp_design.html)
- Datasets:
    - [Poundhill Data](data/PoundHillData.csv)
    - [Poundhill Meta Data](data/PoundHillMetaData.csv)
    - [Huxley et al Trait Data](data/traitdata_Huxleyetal_2021.csv)
    - [Genome Size](data/GenomeSize.csv)
    - [Wrangling Practical Data](data/wranglingdataset.csv)

### Introduction to Linear Models

- [Lecture Slides](lectures/VB_LinMods.pdf), [Lecture Video 1](https://www.youtube.com/watch?v=oqjzfXDgZY0&list=PLrMhLVyZEsORr81gXrfgiq2vX30_brtpF&index=2), [Lecture Video 2](https://www.youtube.com/watch?v=-VelMqc9z6M&list=PLrMhLVyZEsORr81gXrfgiq2vX30_brtpF&index=1), [Practical](activities/VB_Linear_models_activity.html)
- Datasets:
    - [Genome Size](data/GenomeSize.csv)
    - [Huxley et al Trait Data](data/traitdata_Huxleyetal_2021.csv)
    - [Linear Models Practical Data](data/lmdataset.csv)
    
<br>
<br>

# Intermediate materials

### Nonlinear Modeling (including Thermal Performance Curves -- TPCs)

- [Lecture Slides](lectures/VB_NLLS.pdf), [Lecture Video](https://www.youtube.com/watch?v=dnZlU2_iQ1k&list=PLrMhLVyZEsORr81gXrfgiq2vX30_brtpF&index=3), [Practical](activities/VB_NLLS_activity.html)
- Datasets:
    - [csm7I Data](data/csm7I.csv)
    - [Aedes Juvenile Mortality Data](data/juvenilemortalityrateae.csv)
    - [NLLS Practical Data](data/nllsdataset.csv)
    

### Simple Models for Temporal Data (based on Linear Models)

- [Lecture Slides](lectures/VB_TS.pdf),  [Lecture Video](https://www.youtube.com/watch?v=CIAoauEoTTo&list=PLrMhLVyZEsORr81gXrfgiq2vX30_brtpF&index=5), [Practical](activities/VB_TimeSeries.html), [Airline "solution"](activities/VB_TS_exercise_soln.html)
- Datasets:
    - [Culex erraticus Data](data/Culex_erraticus_walton.csv)
    - [Culex nigripalpus Manatee County Data](data/Culex_nigripalpus_manatee.csv)
    - [Culex nigripalpus Walton County Data](data/Culex_nigripalpus_walton.csv)
    - [Climate Data](data/vectorbase_locations_dates_climate.csv)
    - [Airline Data](data/airline.csv)
    


### Review of Likelihoods 

- [Lecture Slides](lectures/VB_likelihood.pdf),  [Lecture Video](https://www.youtube.com/watch?v=MQOI91UMDX4&list=PLrMhLVyZEsORr81gXrfgiq2vX30_brtpF&index=7), [Practical](activities/VB_likelihood_activity.html)


<br>
<br>

# Advanced materials

### Bayesian Basics 

- [Lecture Slides](lectures/VB_Bayes1.pdf),  [Lecture Video](https://www.youtube.com/watch?v=sVtaTTIZEa4&list=PLrMhLVyZEsORr81gXrfgiq2vX30_brtpF&index=4), [Analytic Practical](activities/VB_Bayes_activity1.html) 
- Datasets:
    - [Midge Length Data](data/MidgeWingLength.csv)


### Fitting Bayesian Models Using JAGS

- [Lecture Slides](lectures/VB_Bayes2.pdf),  [Lecture Video](https://www.youtube.com/watch?v=mQQV0Isn_lY&list=PLrMhLVyZEsORr81gXrfgiq2vX30_brtpF&index=11), [Computational Practical](activities/VB_Bayes_activity2.html) 
- Datasets:
    - [Midge Length Data](data/MidgeWingLength.csv)
    - [Aedes Trait Data](data/AeaegyptiTraitData.csv)


### Introduction to Bayesian State-Space models for Temporal Data
- [Lecture Slides 1](lectures/vb_state_space1.pdf), [Lecture Slides 2](lectures/vb_state_space2.pdf), [Lecture Slides 3](lectures/vb_state_space3.pdf), [Lecture Video 1](https://www.youtube.com/watch?v=-hvOaRwf6Mw), [Lecture Video 2](https://www.youtube.com/watch?v=d_gegj-Cc4I), [Lecture Video 3](https://www.youtube.com/watch?v=jHzwODN7E34), [Modeling Activity](activities/SSM_activity.html)

